### PR TITLE
viewer: fix sort order button hitbox

### LINKED ISSUE #266: viewer: fix sort order button hitbox
The hitbox is too small, making it hard to open the menu on touchscreens. It should be normalised like for the other buttons in the "toolbar".

### PR DESCRIPTION
**Pull request by zeroinformatique**
github: resolves #266

### CODE REVIEW

**Review by pacien — CHANGES_REQUESTED** [review]
The hitbox is now correct __but the hover-box isn't__; the cursor changes to a pointer before the icon colour changes as you get closer to the icon.

**Review by pacien — CHANGES_REQUESTED** [review]
The hit and hover boxes are now correct, but __this button generates two clickable boxes instead of one__. This is capturing the focus twice and hinders keyboard navigation.

**Comment by zeroinformatique** [comment]
I created this new issue for the focus problem: https://github.com/pacien/ldgallery/issues/275
This PR seems to fix the original request, I guess we can merge.

**Review by pacien — APPROVED** [review]
Let's take care of the focus issue later. The rest LGTM.

**Pull request merged**
