### PR TITLE
compiler: metadata sidecar for whole directories

### LINKED ISSUE #3: Sidecar metadata file for directories
The user should be able to add descriptions to directories too, and perhaps specify tags that would apply to all items within it at once.

Sidecar files for directories would need to be introduced.

### PR DESCRIPTION
**Pull request by pacien**
GitHub: closes #3

### CODE REVIEW

**Comment by OzoneGrif** [comment]
A few comments:
- I don't like the fact that you have two files with different names to describe a directory: "thumbnail.jpg" and "directory.yaml". They should have the same name.
- "directory" and "thumbnail" are common words, they could easily conflict with a gallery's content. Tested on my data, "thumbnail" does conflict in quite a few cases. I suggest "this_directory.jpg" and "this_directory.yaml" as an alternative.
- What are the difference between the root directory's title and the gallery's name? You set both in the example gallery with the same string.
- Don't remove the commented default values from the example gallery. We need an example as complete as possible for our users. Actually, we should make sure the example is exhaustive.

**Comment by OzoneGrif** [comment]
You removed the option "TagsFromDirectories", please put it back.
The directory yaml files are not a replacement for this option.

**Comment by OzoneGrif** [comment]
You removed the gallery name, but when there is no directory.yaml file in the root, it will display an empty home icon in the gallery. It looks like a button, which is not correct.
Directory.yaml files have to remain 100% optional for the gallery to work properly.

**Comment by pacien** [comment]
(Please use the GitHub review feature.)

> * I don't like the fact that you have two files with different names to describe a directory: "thumbnail.jpg" and "directory.yaml". They should have the same name.
> * "directory" and "thumbnail" are common words, they could easily conflict with a gallery's content. Tested on my data, "thumbnail" does conflict in quite a few cases. I suggest "this_directory.jpg" and "this_directory.yaml" as an alternative.

Fixed: renamed both to `_directory.{[img ext], yaml}`.

> * Don't remove the commented default values from the example gallery. We need an example as complete as possible for our users. Actually, we should make sure the example is exhaustive.

Removed examples correspond to removed options.

> * You removed the option "TagsFromDirectories", please put it back.
>   The directory yaml files are not a replacement for this option; they are a complement.

Directory tags are more flexible. I'd like to avoid option bloat which leads to conflicting behaviours for now. We may do directory tags differently to cover #59.

> * You removed the gallery name, but when there is no directory.yaml file in the root, it will display an empty home icon in the gallery. It looks like a button, which is not correct.
>   Directory.yaml files have to remain 100% optional for the gallery to work properly.

This is not a problem and I actually like it that way for unnamed galleries.

Thinking back about the usefulness of the home button, it is redundant with the breadcrumbs. We might as well remove it and used the free room for another more useful button later.

**Comment by OzoneGrif** [comment]
> Fixed: renamed both to _directory.{[img ext], yaml}.
Ok

> Directory tags are more flexible. I'd like to avoid option bloat which leads to conflicting behaviours for now. We may do directory tags differently to cover #59.
Like I said, this is not a replacement, this is a supplement. Do not remove this functionality. It is optional, users are not obligated to use it, but it is mandatory to make users' life easier when they do not want to tag each folder individually. Please put it back.

> Thinking back about the usefulness of the home button, it is redundant with the breadcrumbs. We might as well remove it and used the free room for another more useful button later.

Yes, we can remove the home button, in that case.

**Comment by pacien** [comment]
> Like I said, this is not a replacement, this is a supplement. Do not remove this functionality. It is optional, users are not obligated to use it, but it is mandatory to make users' life easier when they do not want to tag each folder individually. Please put it back or propose a recursive, auto-tag, alternative.

Ok, the `tagsFromDirectories` option has been restored. It might however change when handling #59.

**Pull request merged**
